### PR TITLE
Ignore debug plugins included in Quickstart

### PR DESCRIPTION
**Pull request by philipjohn**
Ignores the debug plugins added by Quickstart (see https://github.com/Automattic/vip-go-quickstart/commit/82208ade49621da7a85f40e7ba43bd79930c8e70)

### CODE REVIEW

**Comment by simonwheatley** [comment]
@philipjohn What's your thinking here? I'm wondering what happens if the developers want to push User Switching or whatever into staging or production.

**Comment by philipjohn** [comment]
Hmm, I hadn't thought about staging.

As for production, I was thinking having these in production would be undesirable?

**Comment by simonwheatley** [comment]
I think we should do this somewhere else, if we decide we want to.

**Comment by joshbetz** [comment]
After thinking about this some more, I think the skeleton repo is actually the best place for this. By default you wouldn't want these plugins in production. If someone does, they can simply remove them from their `.gitignore` after forking this.

**Comment by joshbetz** [comment]
Merging this and we can revert later if there are problems. :shipit:

**Pull request merged**
